"""Curated starter learning material; not an official JLPT syllabus."""

LESSONS = [
 {"id":"hiragana-vowels","title":"Hiragana: the five vowels","level":"N5","category":"Hiragana","minutes":5,"objective":"Recognize and read あ・い・う・え・お.","intro":"Hiragana represents Japanese sounds. Begin with five vowel characters; their order is a, i, u, e, o.","explanation":"Read each character aloud. The vowels stay consistent in other kana.","examples":[{"ja":"あ","reading":"あ","romaji":"a","en":"the vowel a"},{"ja":"い","reading":"い","romaji":"i","en":"the vowel i"},{"ja":"う","reading":"う","romaji":"u","en":"the vowel u"},{"ja":"え","reading":"え","romaji":"e","en":"the vowel e"},{"ja":"お","reading":"お","romaji":"o","en":"the vowel o"}],"exercise":{"prompt":"Which hiragana is read as 'u'?","choices":["あ","い","う","え"],"answer":"う","explanation":"う is read as u."},"source_note":"Curated beginner practice; not an official JLPT lesson."},
 {"id":"greetings","title":"Everyday greetings","level":"N5","category":"Conversation","minutes":6,"objective":"Choose a greeting that fits the time of day.","intro":"Japanese greetings depend on context and time. These are common, polite starter expressions.","explanation":"こんにちは works as a daytime hello. おはようございます is a polite morning greeting. こんばんは is used in the evening.","examples":[{"ja":"おはようございます。","reading":"おはようございます","romaji":"ohayou gozaimasu","en":"Good morning."},{"ja":"こんにちは。","reading":"こんにちは","romaji":"konnichiwa","en":"Hello / good afternoon."},{"ja":"こんばんは。","reading":"こんばんは","romaji":"konbanwa","en":"Good evening."}],"exercise":{"prompt":"Which greeting means 'Good evening'?","choices":["おはようございます","こんにちは","こんばんは","ありがとう"],"answer":"こんばんは","explanation":"こんばんは is the usual evening greeting."},"source_note":"Curated beginner practice; translations depend on context."},
 {"id":"sentence-desu","title":"A simple sentence with です","level":"N5","category":"Grammar","minutes":7,"objective":"Use です to make a polite statement.","intro":"です (desu) makes many noun statements polite. Japanese often leaves out a subject clear from context.","explanation":"Pattern: [noun] + です. English translation depends on context; です is not always a separate word.","examples":[{"ja":"学生です。","reading":"がくせいです","romaji":"gakusei desu","en":"(I am / you are) a student."},{"ja":"水です。","reading":"みずです","romaji":"mizu desu","en":"It is water."}],"exercise":{"prompt":"Complete: 学生 ___。","choices":["です","ます","を","に"],"answer":"です","explanation":"です forms a polite noun statement."},"source_note":"Curated grammar note; not an official JLPT lesson."},
 {"id":"particle-wa","title":"Topic marker は","level":"N5","category":"Grammar","minutes":8,"objective":"Identify は as the topic marker, pronounced wa in this use.","intro":"The particle は marks what a sentence is about. As a particle, it is written は but pronounced wa.","explanation":"Pattern: topic + は + comment. The particle reading differs from は inside other words.","examples":[{"ja":"私は学生です。","reading":"わたしはがくせいです","romaji":"watashi wa gakusei desu","en":"I am a student."},{"ja":"これは本です。","reading":"これはほんです","romaji":"kore wa hon desu","en":"This is a book."}],"exercise":{"prompt":"In 私は学生です, how is the particle は pronounced?","choices":["ha","wa","he","o"],"answer":"wa","explanation":"The topic particle は is pronounced wa."},"source_note":"Curated grammar note; not an official JLPT lesson."},
 {"id":"katakana-first","title":"Katakana: a first look","level":"N5","category":"Katakana","minutes":6,"objective":"Recognize a few common katakana characters and understand model limits.","intro":"Katakana is commonly used for loanwords and names. This app's handwriting classifier is trained for hiragana; type or correct katakana images.","explanation":"Learn the shapes separately: ア is a, イ is i, ウ is u, エ is e.","examples":[{"ja":"ア","reading":"あ","romaji":"a","en":"katakana a"},{"ja":"イ","reading":"い","romaji":"i","en":"katakana i"},{"ja":"ウ","reading":"う","romaji":"u","en":"katakana u"},{"ja":"コーヒー","reading":"こーひー","romaji":"koohii","en":"coffee"}],"exercise":{"prompt":"Which katakana is read as 'i'?","choices":["ア","イ","ウ","エ"],"answer":"イ","explanation":"イ is read as i."},"source_note":"Curated script practice; katakana image recognition is not provided."},
 {"id":"order-japanese","title":"A basic Japanese sentence","level":"N5","category":"Grammar","minutes":8,"objective":"Notice the common subject–object–verb order in a simple sentence.","intro":"Japanese commonly puts the verb near the end. Particles show how words relate to each other.","explanation":"In 私は水を飲みます, は marks the topic, を marks the object, and 飲みます is the verb.","examples":[{"ja":"私は水を飲みます。","reading":"わたしはみずをのみます","romaji":"watashi wa mizu o nomimasu","en":"I drink water."},{"ja":"本を読みます。","reading":"ほんをよみます","romaji":"hon o yomimasu","en":"(I) read a book."}],"exercise":{"prompt":"Which word is the verb in 私は水を飲みます?","choices":["私","水","を","飲みます"],"answer":"飲みます","explanation":"飲みます (nomimasu) is the verb 'drink'."},"source_note":"Curated grammar note; omitted subjects depend on context."},
 {"id":"request-kudasai","title":"Make a polite request","level":"N5","category":"Conversation","minutes":7,"objective":"Use ください to ask for an item politely.","intro":"ください after a requested item means 'please give me' or 'please provide'. It is useful in shops and restaurants.","explanation":"Pattern: item + を + ください. Counters vary; begin with a memorized phrase.","examples":[{"ja":"水をください。","reading":"みずをください","romaji":"mizu o kudasai","en":"Water, please."},{"ja":"コーヒーを一つください。","reading":"こーひーをひとつください","romaji":"koohii o hitotsu kudasai","en":"One coffee, please."}],"exercise":{"prompt":"Choose the polite request for water.","choices":["水をください。","水がです。","ください水を。","水でください。"],"answer":"水をください。","explanation":"水をください is a common polite request for water."},"source_note":"Curated phrase; counters and politeness vary with context."},
 {"id":"ask-location","title":"Ask where something is","level":"N5","category":"Travel","minutes":7,"objective":"Ask where a place or object is.","intro":"どこですか asks where something is. Add the place before は for a clear question.","explanation":"Pattern: [place] は どこですか. Add すみません at the start politely.","examples":[{"ja":"駅はどこですか。","reading":"えきはどこですか","romaji":"eki wa doko desu ka","en":"Where is the station?"},{"ja":"すみません、トイレはどこですか。","reading":"すみません、といれはどこですか","romaji":"sumimasen, toire wa doko desu ka","en":"Excuse me, where is the restroom?"}],"exercise":{"prompt":"Which means 'Where is the station?'","choices":["駅はどこですか。","駅をください。","駅です。","駅はだれですか。"],"answer":"駅はどこですか。","explanation":"駅はどこですか asks where the station is."},"source_note":"Curated travel phrase; not an official JLPT lesson."}
]



LESSONS.extend([
 {"id":"n4-te-iru","title":"Describe an action in progress","level":"N4","category":"Grammar","minutes":8,"objective":"Use ています for an action happening now.","intro":"The ている form often describes an action in progress. Context can also make it describe a continuing state or habit.","explanation":"Change a verb to its て-form and add います. For example, 読む → 読んでいます.","examples":[{"ja":"今、本を読んでいます。","reading":"いま、ほんをよんでいます","en":"I am reading a book now."},{"ja":"日本語を勉強しています。","reading":"にほんごをべんきょうしています","en":"I am studying Japanese."}],"exercise":{"prompt":"Choose ‘I am eating now.’","choices":["今、食べています。","今、食べました。","今、食べません。","今、食べたいです。"],"answer":"今、食べています。","explanation":"食べています is the polite ている form of 食べる."},"source_note":"Curated N4 practice; not an official JLPT lesson."},
 {"id":"n4-experience","title":"Talk about experience with ことがある","level":"N4","category":"Grammar","minutes":8,"objective":"Ask whether someone has done something before.","intro":"A verb in past plain form + ことがあります can describe life experience.","explanation":"Pattern: verbた + ことがあります. It differs from a simple past event with a specific time.","examples":[{"ja":"日本へ行ったことがあります。","reading":"にほんへいったことがあります","en":"I have been to Japan."},{"ja":"すしを食べたことがありますか。","reading":"すしをたべたことがありますか","en":"Have you eaten sushi before?"}],"exercise":{"prompt":"Which asks ‘Have you seen this film before?’","choices":["この映画を見たことがありますか。","この映画を見ていますか。","この映画を見ませんでした。","この映画を見たいです。"],"answer":"この映画を見たことがありますか。","explanation":"見たことがあります asks about prior experience."},"source_note":"Curated N4 practice; not an official JLPT lesson."},
 {"id":"n3-youni","title":"Describe a change with ようになる","level":"N3","category":"Grammar","minutes":9,"objective":"Describe something that has become possible or habitual.","intro":"ようになる can describe a change in ability or behavior over time.","explanation":"A potential verb or dictionary-form verb + ようになる describes a resulting ability or habit.","examples":[{"ja":"漢字が読めるようになりました。","reading":"かんじがよめるようになりました","en":"I became able to read kanji."},{"ja":"毎朝走るようになりました。","reading":"まいあさはしるようになりました","en":"I have started running every morning."}],"exercise":{"prompt":"Choose ‘I became able to speak Japanese.’","choices":["日本語が話せるようになりました。","日本語を話したことがあります。","日本語を話すそうです。","日本語を話さないでください。"],"answer":"日本語が話せるようになりました。","explanation":"話せるようになりました describes a new ability."},"source_note":"Curated N3 practice; not an official JLPT lesson."},
 {"id":"n3-soudesu","title":"Report what you heard with そうです","level":"N3","category":"Grammar","minutes":8,"objective":"Pass on information heard from another source.","intro":"そうです can mark hearsay: ‘I hear that…’ or ‘Apparently…’.","explanation":"Attach そうです to the plain form of a sentence. This is different from the appearance pattern そうです after a verb stem or adjective stem.","examples":[{"ja":"天気予報によると、明日は雨だそうです。","reading":"てんきよほうによると、あしたはあめだそうです","en":"According to the forecast, I hear it will rain tomorrow."},{"ja":"田中さんは来ないそうです。","reading":"たなかさんはこないそうです","en":"I hear Tanaka is not coming."}],"exercise":{"prompt":"Choose ‘I hear the train is delayed.’","choices":["電車が遅れているそうです。","電車が遅れそうです。","電車を遅れました。","電車が遅れるようにです。"],"answer":"電車が遅れているそうです。","explanation":"The plain clause + そうです reports information heard."},"source_note":"Curated N3 practice; not an official JLPT lesson."},
 {"id":"n2-wakedehanai","title":"Qualify a statement with わけではない","level":"N2","category":"Grammar","minutes":9,"objective":"Say that something is not necessarily true.","intro":"わけではない softens a broad conclusion: ‘it does not mean that…’ or ‘not necessarily…’.","explanation":"Attach it to a plain clause. It often corrects a possible misunderstanding rather than denying everything outright.","examples":[{"ja":"毎日忙しいわけではありません。","reading":"まいにちいそがしいわけではありません","en":"It is not as if I am busy every day."},{"ja":"高ければいいというわけではない。","reading":"たかければいいというわけではない","en":"More expensive does not necessarily mean better."}],"exercise":{"prompt":"Choose ‘It does not mean that I dislike Japanese food.’","choices":["日本料理が嫌いなわけではありません。","日本料理が嫌いに違いありません。","日本料理が嫌いなはずです。","日本料理が嫌い次第です。"],"answer":"日本料理が嫌いなわけではありません。","explanation":"わけではありません rejects an assumed conclusion without making the opposite absolute."},"source_note":"Curated N2 practice; not an official JLPT lesson."},
 {"id":"n2-ni-chigainai","title":"Make a strong inference with に違いない","level":"N2","category":"Grammar","minutes":8,"objective":"Express a confident conclusion from evidence.","intro":"に違いない means ‘must be’ or ‘there is no doubt that’ based on the speaker's inference.","explanation":"Attach に違いない to a plain form. Use it for a strong belief, not a directly observed fact that needs no inference.","examples":[{"ja":"電気がついている。誰かいるに違いない。","reading":"でんきがついている。だれかいるにちがいない","en":"The light is on. Someone must be there."},{"ja":"彼はもう駅に着いたに違いない。","reading":"かれはもうえきについたにちがいない","en":"He must have arrived at the station by now."}],"exercise":{"prompt":"Choose ‘She must be tired after working all day.’","choices":["一日働いたので、彼女は疲れているに違いない。","一日働いたので、彼女は疲れたことがある。","一日働いたので、彼女は疲れるように。","一日働いたので、彼女は疲れないわけだ。"],"answer":"一日働いたので、彼女は疲れているに違いない。","explanation":"に違いない marks the speaker's strong inference."},"source_note":"Curated N2 practice; not an official JLPT lesson."},
 {"id":"n1-hokanai","title":"Describe the only remaining option with ほかない","level":"N1","category":"Grammar","minutes":10,"objective":"Describe an outcome as unavoidable given the circumstances.","intro":"ほかない is a formal expression meaning that there is no choice but to do something. It describes an option presented as unavoidable in context.","explanation":"Verb dictionary form + ほかない expresses the only remaining option. This pattern is formal and context-sensitive.","examples":[{"ja":"電車が止まったので、歩くほかない。","reading":"でんしゃがとまったので、あるくほかない","en":"The trains stopped, so there is no choice but to walk."},{"ja":"期限が近いから、今始めるほかない。","reading":"きげんがちかいから、いまはじめるほかない","en":"The deadline is close, so we have no choice but to start now."}],"exercise":{"prompt":"Choose ‘There is no choice but to wait.’","choices":["待つほかない。","待ったことがある。","待つわけではない。","待てるようになった。"],"answer":"待つほかない。","explanation":"Dictionary form + ほかない describes the sole remaining option."},"source_note":"Curated advanced grammar practice; nuance depends on context and is not official JLPT material."},
 {"id":"n1-kagiri","title":"Set a limit with 限り","level":"N1","category":"Grammar","minutes":10,"objective":"Describe a conclusion within the limits of available knowledge.","intro":"As far as / to the extent that can be known or observed can be expressed with 限り.","explanation":"Expressions such as 私の知る限り mean ‘as far as I know’. The phrase sets a limit on the speaker's claim.","examples":[{"ja":"私の知る限り、変更はありません。","reading":"わたしのしるかぎり、へんこうはありません","en":"As far as I know, there have been no changes."},{"ja":"見た限りでは、問題なさそうです。","reading":"みたかぎりでは、もんだいなさそうです","en":"As far as I can tell, there does not seem to be a problem."}],"exercise":{"prompt":"Choose ‘As far as I know, he is not here.’","choices":["私の知る限り、彼はいません。","私が知ることがあり、彼はいません。","私の知るわけではなく、彼はいません。","私が知るように、彼はいません。"],"answer":"私の知る限り、彼はいません。","explanation":"私の知る限り is a common expression for ‘as far as I know’."},"source_note":"Curated advanced grammar practice; not an official JLPT lesson."}
])

SCENARIOS = [
 {"id":"restaurant","title":"Order at a restaurant","level":"N5","goal":"Order one item and respond to a follow-up.","vocabulary":["注文（ちゅうもん）— order","ください — please give me","水（みず）— water"],"turns":[
  {"ja":"いらっしゃいませ。ご注文はお決まりですか？","en":"Welcome. Are you ready to order?","suggestions":[{"ja":"ラーメンを一つください。","en":"One ramen, please."},{"ja":"水をください。","en":"Water, please."},{"ja":"おすすめは何ですか？","en":"What do you recommend?"}]},
  {"ja":"かしこまりました。お飲み物はいかがですか？","en":"Certainly. Would you like a drink?","suggestions":[{"ja":"水をお願いします。","en":"Water, please."},{"ja":"お茶をください。","en":"Tea, please."}]},
  {"ja":"ありがとうございます。ごゆっくりどうぞ。","en":"Thank you. Please enjoy your meal.","suggestions":[]}]},
 {"id":"station","title":"Ask for directions at a station","level":"N5","goal":"Ask where a platform or station exit is.","vocabulary":["駅（えき）— station","出口（でぐち）— exit","どこ — where"],"turns":[
  {"ja":"こんにちは。どちらへ行きますか？","en":"Hello. Where are you going?","suggestions":[{"ja":"新宿駅へ行きたいです。","en":"I want to go to Shinjuku Station."},{"ja":"すみません、出口はどこですか？","en":"Excuse me, where is the exit?"}]},
  {"ja":"わかりました。切符をお持ちですか？","en":"All right. Do you have a ticket?","suggestions":[{"ja":"はい、持っています。","en":"Yes, I do."},{"ja":"いいえ、まだです。","en":"No, not yet."}]},
  {"ja":"ありがとうございます。気をつけて行ってください。","en":"Thank you. Have a safe trip.","suggestions":[]}]},
 {"id":"self-introduction","title":"Introduce yourself","level":"N5","goal":"Say your name and one thing about yourself.","vocabulary":["名前（なまえ）— name","学生（がくせい）— student","よろしくお願いします — nice to meet you"],"turns":[
  {"ja":"こんにちは。お名前は何ですか？","en":"Hello. What is your name?","suggestions":[{"ja":"サムです。","en":"I'm Sam."},{"ja":"私の名前はサムです。","en":"My name is Sam."}]},
  {"ja":"はじめまして。どこから来ましたか？","en":"Nice to meet you. Where are you from?","suggestions":[{"ja":"インドから来ました。","en":"I'm from India."},{"ja":"インド出身です。","en":"I'm from India."}]},
  {"ja":"そうですか。よろしくお願いします！","en":"I see. Nice to meet you!","suggestions":[]}]},
 {"id":"konbini","title":"At a convenience store","level":"N5","goal":"Ask for an item and answer a simple checkout question.","vocabulary":["これ — this","ください — please give me","袋（ふくろ）— bag"],"turns":[
  {"ja":"いらっしゃいませ。","en":"Welcome.","suggestions":[{"ja":"おにぎりをください。","en":"An onigiri, please."},{"ja":"これをください。","en":"This one, please."}]},
  {"ja":"温めますか？","en":"Would you like it warmed up?","suggestions":[{"ja":"はい、お願いします。","en":"Yes, please."},{"ja":"いいえ、大丈夫です。","en":"No, that's okay."}]},
  {"ja":"ありがとうございました。","en":"Thank you very much.","suggestions":[]}]}
]

SCENARIOS.extend([
 {"id":"hotel","title":"Check into a hotel","level":"N4","goal":"Give a reservation name and ask about check-out.","vocabulary":["予約（よやく）— reservation","名前（なまえ）— name","チェックアウト — check-out"],"turns":[
  {"ja":"いらっしゃいませ。ご予約のお名前をお願いします。","en":"Welcome. May I have the name on your reservation?","suggestions":[{"ja":"サムの名前で予約しました。","en":"I have a reservation under Sam."},{"ja":"予約していません。","en":"I don't have a reservation."}]},
  {"ja":"ありがとうございます。こちらにご記入ください。","en":"Thank you. Please fill this out.","suggestions":[{"ja":"はい、わかりました。","en":"Yes, understood."},{"ja":"チェックアウトは何時ですか？","en":"What time is check-out?"}]},
  {"ja":"チェックアウトは午前十時です。","en":"Check-out is at ten in the morning.","suggestions":[]}]},
 {"id":"make-reservation","title":"Make a restaurant reservation","level":"N3","goal":"Ask whether a table is available and give a party size.","vocabulary":["予約（よやく）— reservation","人数（にんずう）— number of people","空く（あく）— to be available"],"turns":[
  {"ja":"お電話ありがとうございます。何名様でしょうか？","en":"Thank you for calling. How many people?","suggestions":[{"ja":"二人です。","en":"Two people."},{"ja":"三人でお願いします。","en":"For three, please."}]},
  {"ja":"何時をご希望ですか？","en":"What time would you prefer?","suggestions":[{"ja":"午後七時を希望します。","en":"I'd like seven in the evening."},{"ja":"六時半は空いていますか？","en":"Is six thirty available?"}]},
  {"ja":"確認いたします。少々お待ちください。","en":"I'll check. Please wait a moment.","suggestions":[]}]},
 {"id":"doctor","title":"Describe a simple symptom","level":"N3","goal":"Tell clinic staff what hurts and when it started.","vocabulary":["痛い（いたい）— painful","昨日（きのう）— yesterday","病院（びょういん）— hospital"],"turns":[
  {"ja":"今日はどうされましたか？","en":"What brings you in today?","suggestions":[{"ja":"頭が痛いです。","en":"I have a headache."},{"ja":"昨日から熱があります。","en":"I have had a fever since yesterday."}]},
  {"ja":"いつから症状がありますか？","en":"When did the symptoms start?","suggestions":[{"ja":"今朝からです。","en":"Since this morning."},{"ja":"三日前からです。","en":"Since three days ago."}]},
  {"ja":"わかりました。診察します。","en":"I understand. I'll examine you now.","suggestions":[]}]},
 {"id":"work-interview","title":"Answer a job interview question","level":"N2","goal":"Give a brief reason for applying and one strength.","vocabulary":["応募（おうぼ）— application","経験（けいけん）— experience","強み（つよみ）— strength"],"turns":[
  {"ja":"弊社に応募された理由を教えてください。","en":"Please tell me why you applied to our company.","suggestions":[{"ja":"御社のサービスに関心があるからです。","en":"I am interested in your company's services."},{"ja":"これまでの経験を活かしたいと思ったからです。","en":"I want to make use of my past experience."}]},
  {"ja":"ご自身の強みは何だと思いますか？","en":"What do you consider your strengths?","suggestions":[{"ja":"最後まで責任を持って取り組みます。","en":"I take responsibility and follow through."},{"ja":"新しいことを学ぶのが得意です。","en":"I am good at learning new things."}]},
  {"ja":"ありがとうございます。","en":"Thank you.","suggestions":[]}]}
])
