"""Curated starter learning material; not an official JLPT syllabus."""

LESSONS = [
 {"id":"hiragana-vowels","title":"Hiragana: the five vowels","level":"N5","category":"Hiragana","minutes":5,"objective":"Recognize and read あ・い・う・え・お.","intro":"Hiragana represents Japanese sounds. Begin with five vowel characters; their order is a, i, u, e, o.","explanation":"Read each character aloud. The vowels stay consistent in other kana.","examples":[{"ja":"あ","reading":"a","en":"the vowel a"},{"ja":"い","reading":"i","en":"the vowel i"},{"ja":"う","reading":"u","en":"the vowel u"},{"ja":"え","reading":"e","en":"the vowel e"},{"ja":"お","reading":"o","en":"the vowel o"}],"exercise":{"prompt":"Which hiragana is read as 'u'?","choices":["あ","い","う","え"],"answer":"う","explanation":"う is read as u."},"source_note":"Curated beginner practice; not an official JLPT lesson."},
 {"id":"greetings","title":"Everyday greetings","level":"N5","category":"Conversation","minutes":6,"objective":"Choose a greeting that fits the time of day.","intro":"Japanese greetings depend on context and time. These are common, polite starter expressions.","explanation":"こんにちは works as a daytime hello. おはようございます is a polite morning greeting. こんばんは is used in the evening.","examples":[{"ja":"おはようございます。","reading":"ohayou gozaimasu","en":"Good morning."},{"ja":"こんにちは。","reading":"konnichiwa","en":"Hello / good afternoon."},{"ja":"こんばんは。","reading":"konbanwa","en":"Good evening."}],"exercise":{"prompt":"Which greeting means 'Good evening'?","choices":["おはようございます","こんにちは","こんばんは","ありがとう"],"answer":"こんばんは","explanation":"こんばんは is the usual evening greeting."},"source_note":"Curated beginner practice; translations depend on context."},
 {"id":"sentence-desu","title":"A simple sentence with です","level":"N5","category":"Grammar","minutes":7,"objective":"Use です to make a polite statement.","intro":"です (desu) makes many noun statements polite. Japanese often leaves out a subject clear from context.","explanation":"Pattern: [noun] + です. English translation depends on context; です is not always a separate word.","examples":[{"ja":"学生です。","reading":"gakusei desu","en":"(I am / you are) a student."},{"ja":"水です。","reading":"mizu desu","en":"It is water."}],"exercise":{"prompt":"Complete: 学生 ___。","choices":["です","ます","を","に"],"answer":"です","explanation":"です forms a polite noun statement."},"source_note":"Curated grammar note; not an official JLPT lesson."},
 {"id":"particle-wa","title":"Topic marker は","level":"N5","category":"Grammar","minutes":8,"objective":"Identify は as the topic marker, pronounced wa in this use.","intro":"The particle は marks what a sentence is about. As a particle, it is written は but pronounced wa.","explanation":"Pattern: topic + は + comment. The particle reading differs from は inside other words.","examples":[{"ja":"私は学生です。","reading":"watashi wa gakusei desu","en":"I am a student."},{"ja":"これは本です。","reading":"kore wa hon desu","en":"This is a book."}],"exercise":{"prompt":"In 私は学生です, how is the particle は pronounced?","choices":["ha","wa","he","o"],"answer":"wa","explanation":"The topic particle は is pronounced wa."},"source_note":"Curated grammar note; not an official JLPT lesson."},
 {"id":"katakana-first","title":"Katakana: a first look","level":"N5","category":"Katakana","minutes":6,"objective":"Recognize a few common katakana characters and understand model limits.","intro":"Katakana is commonly used for loanwords and names. This app's handwriting classifier is trained for hiragana; type or correct katakana images.","explanation":"Learn the shapes separately: ア is a, イ is i, ウ is u, エ is e.","examples":[{"ja":"ア","reading":"a","en":"katakana a"},{"ja":"イ","reading":"i","en":"katakana i"},{"ja":"ウ","reading":"u","en":"katakana u"},{"ja":"コーヒー","reading":"koohii","en":"coffee"}],"exercise":{"prompt":"Which katakana is read as 'i'?","choices":["ア","イ","ウ","エ"],"answer":"イ","explanation":"イ is read as i."},"source_note":"Curated script practice; katakana image recognition is not provided."},
 {"id":"order-japanese","title":"A basic Japanese sentence","level":"N5","category":"Grammar","minutes":8,"objective":"Notice the common subject–object–verb order in a simple sentence.","intro":"Japanese commonly puts the verb near the end. Particles show how words relate to each other.","explanation":"In 私は水を飲みます, は marks the topic, を marks the object, and 飲みます is the verb.","examples":[{"ja":"私は水を飲みます。","reading":"watashi wa mizu o nomimasu","en":"I drink water."},{"ja":"本を読みます。","reading":"hon o yomimasu","en":"(I) read a book."}],"exercise":{"prompt":"Which word is the verb in 私は水を飲みます?","choices":["私","水","を","飲みます"],"answer":"飲みます","explanation":"飲みます (nomimasu) is the verb 'drink'."},"source_note":"Curated grammar note; omitted subjects depend on context."},
 {"id":"request-kudasai","title":"Make a polite request","level":"N5","category":"Conversation","minutes":7,"objective":"Use ください to ask for an item politely.","intro":"ください after a requested item means 'please give me' or 'please provide'. It is useful in shops and restaurants.","explanation":"Pattern: item + を + ください. Counters vary; begin with a memorized phrase.","examples":[{"ja":"水をください。","reading":"mizu o kudasai","en":"Water, please."},{"ja":"コーヒーを一つください。","reading":"koohii o hitotsu kudasai","en":"One coffee, please."}],"exercise":{"prompt":"Choose the polite request for water.","choices":["水をください。","水がです。","ください水を。","水でください。"],"answer":"水をください。","explanation":"水をください is a common polite request for water."},"source_note":"Curated phrase; counters and politeness vary with context."},
 {"id":"ask-location","title":"Ask where something is","level":"N5","category":"Travel","minutes":7,"objective":"Ask where a place or object is.","intro":"どこですか asks where something is. Add the place before は for a clear question.","explanation":"Pattern: [place] は どこですか. Add すみません at the start politely.","examples":[{"ja":"駅はどこですか。","reading":"eki wa doko desu ka","en":"Where is the station?"},{"ja":"すみません、トイレはどこですか。","reading":"sumimasen, toire wa doko desu ka","en":"Excuse me, where is the restroom?"}],"exercise":{"prompt":"Which means 'Where is the station?'","choices":["駅はどこですか。","駅をください。","駅です。","駅はだれですか。"],"answer":"駅はどこですか。","explanation":"駅はどこですか asks where the station is."},"source_note":"Curated travel phrase; not an official JLPT lesson."}
]

SCENARIOS = [
 {"id":"restaurant","title":"Order at a restaurant","level":"N5","goal":"Order one item and respond to a follow-up.","vocabulary":["注文（ちゅうもん）— order","ください — please give me","水（みず）— water"],"turns":[
  {"ja":"いらっしゃいませ。ご注文はお決まりですか？","en":"Welcome. Are you ready to order?","suggestions":[{"ja":"ラーメンを一つください。","en":"One ramen, please."},{"ja":"水をください。","en":"Water, please."},{"ja":"おすすめは何ですか？","en":"What do you recommend?"}]},
  {"ja":"かしこまりました。お飲み物はいかがですか？","en":"Certainly. Would you like a drink?","suggestions":[{"ja":"水をお願いします。","en":"Water, please."},{"ja":"お茶をください。","en":"Tea, please."}]},
  {"ja":"ありがとうございます。ごゆっくりどうぞ。","en":"Thank you. Please enjoy your meal.","suggestions":[]}]},
 {"id":"station","title":"Ask for directions at a station","level":"N5","goal":"Ask where a platform or station exit is.","vocabulary":["駅（えき）— station","出口（でぐち）— exit","どこ — where"],"turns":[
  {"ja":"こんにちは。どちらへ行きますか？","en":"Hello. Where are you going?","suggestions":[{"ja":"新宿駅へ行きたいです。","en":"I want to go to Shinjuku Station."},{"ja":"すみません、出口はどこですか？","en":"Excuse me, where is the exit?"}]},
  {"ja":"わかりました。切符をお持ちですか？","en":"All right. Do you have a ticket?","suggestions":[{"ja":"はい、持っています。","en":"Yes, I do."},{"ja":"いいえ、まだです。","en":"No, not yet."}]},
  {"ja":"ありがとうございます。気をつけて行ってください。","en":"Thank you. Have a safe trip.","suggestions":[]}]},
 {"id":"self-introduction","title":"Introduce yourself","level":"N5","goal":"Say your name and one thing about yourself.","vocabulary":["名前（なまえ）— name","学生（がくせい）— student","よろしくお願いします — nice to meet you"],"turns":[
  {"ja":"こんにちは。お名前は何ですか？","en":"Hello. What is your name?","suggestions":[{"ja":"サムです。","en":"I'm Sam."},{"ja":"私の名前はサムです。","en":"My name is Sam."}]},
  {"ja":"はじめまして。どこから来ましたか？","en":"Nice to meet you. Where are you from?","suggestions":[{"ja":"インドから来ました。","en":"I'm from India."},{"ja":"インド出身です。","en":"I'm from India."}]},
  {"ja":"そうですか。よろしくお願いします！","en":"I see. Nice to meet you!","suggestions":[]}]},
 {"id":"konbini","title":"At a convenience store","level":"N5","goal":"Ask for an item and answer a simple checkout question.","vocabulary":["これ — this","ください — please give me","袋（ふくろ）— bag"],"turns":[
  {"ja":"いらっしゃいませ。","en":"Welcome.","suggestions":[{"ja":"おにぎりをください。","en":"An onigiri, please."},{"ja":"これをください。","en":"This one, please."}]},
  {"ja":"温めますか？","en":"Would you like it warmed up?","suggestions":[{"ja":"はい、お願いします。","en":"Yes, please."},{"ja":"いいえ、大丈夫です。","en":"No, that's okay."}]},
  {"ja":"ありがとうございました。","en":"Thank you very much.","suggestions":[]}]}
]
